export const initialState = {
  user: null,
  allUsers: null,
  allSongs: null,
  allArtists: null,
  allAlbums: null,
  filterTerm: null,
  filterAlbum: null,
  filterArtist: null,
  filterLanguage: null,
  AlertType: null,
  songPlaying: null,
  songIndex: null,
  isPlayList: false,
  filteredSongs: null,
};
