services:
  - type: web
    name: server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_STRING
        value: mongodb+srv://arunm:1Gm6yMeD4zOOYguX@cluster0.lmxpr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: VITE_IMAGEKIT_PUBLIC_KEY
        value: public_VNd03RHffcl71KVGTGbiiVxGMlg=
      - key: VITE_IMAGEKIT_PRIVATE_KEY
        value: private_DOt/nHS24bVQxjdNjvFp2uOAdAA=
      - key: VITE_IMAGEKIT_URL_ENDPOINT
        value: https://ik.imagekit.io/gmusic

