export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Header } from "./Header";
export { default as Dashboard } from "./Dashboard";
export { default as DashboardHome } from "./DashboardHome";
export { default as DashboardUsers } from "./DashboardUsers";
export { default as DashboardSongs } from "./DashboardSongs";
export { default as DashboardArtist } from "./DashboardArtist";
export { default as DashboardAlbum } from "./DashboardAlbum";
export { default as SongsCard } from "./SongsCard";
export { default as DashboardNewsong } from "./DashboardNewsong";
export { default as FillterButton } from "./FillterButton";
export { default as Upload } from "./Upload";
export { default as Alert } from "./Alert";
export { default as MusicPlayer } from "./MusicPlayer";
export { default as SearchBar } from "./SearchBar";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Musics } from "./Musics";
export { default as Footer } from "./Footer";
export { default as Map } from "./Map";
export { default as NotFound } from "./NotFound";
export { default as Profile } from "./Profile";
export { default as ProfileEdit } from "./ProfileEdit";
// export { default as AuthCallback } from "./AuthCallback";
// export { default as EmailNotVerified } from "./EmailNotVerified";
